-- MySQL Script generated by MySQL Workbench
-- Mon Nov 25 14:40:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbsgbaf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsgbaf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsgbaf` DEFAULT CHARACTER SET utf8 ;
USE `dbsgbaf` ;

-- -----------------------------------------------------
-- Table `dbsgbaf`.`gbaf_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsgbaf`.`gbaf_actor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `logo_file` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsgbaf`.`gbaf_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsgbaf`.`gbaf_member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `question` VARCHAR(255) NOT NULL,
  `answer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsgbaf`.`gbaf_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsgbaf`.`gbaf_comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(45) NOT NULL,
  `date_add` DATETIME NOT NULL,
  `gbaf_actor_id` INT NOT NULL,
  `gbaf_member_id` INT NOT NULL,
  PRIMARY KEY (`id`, `gbaf_actor_id`, `gbaf_member_id`),
  INDEX `fk_gbaf_comment_gbaf_actor1_idx` (`gbaf_actor_id` ASC),
  INDEX `fk_gbaf_comment_gbaf_member1_idx` (`gbaf_member_id` ASC),
  CONSTRAINT `fk_gbaf_comment_gbaf_actor1`
    FOREIGN KEY (`gbaf_actor_id`)
    REFERENCES `dbsgbaf`.`gbaf_actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gbaf_comment_gbaf_member1`
    FOREIGN KEY (`gbaf_member_id`)
    REFERENCES `dbsgbaf`.`gbaf_member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsgbaf`.`gbaf_vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsgbaf`.`gbaf_vote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `like` TINYINT(1) NOT NULL,
  `gbaf_actor_id` INT NOT NULL,
  `gbaf_member_id` INT NOT NULL,
  PRIMARY KEY (`id`, `gbaf_actor_id`, `gbaf_member_id`),
  INDEX `fk_gbaf_vote_gbaf_actor1_idx` (`gbaf_actor_id` ASC),
  INDEX `fk_gbaf_vote_gbaf_member1_idx` (`gbaf_member_id` ASC),
  CONSTRAINT `fk_gbaf_vote_gbaf_actor1`
    FOREIGN KEY (`gbaf_actor_id`)
    REFERENCES `dbsgbaf`.`gbaf_actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gbaf_vote_gbaf_member1`
    FOREIGN KEY (`gbaf_member_id`)
    REFERENCES `dbsgbaf`.`gbaf_member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
